//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Championship_Female {
            get {
                return ResourceManager.GetString("Championship_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Championship_Male {
            get {
                return ResourceManager.GetString("Championship_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string ddlItemCroatian {
            get {
                return ResourceManager.GetString("ddlItemCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ddlItemEnglish {
            get {
                return ResourceManager.GetString("ddlItemEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string ddlItemFemale {
            get {
                return ResourceManager.GetString("ddlItemFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string ddlItemMale {
            get {
                return ResourceManager.GetString("ddlItemMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team.
        /// </summary>
        public static string lblAwayTeam {
            get {
                return ResourceManager.GetString("lblAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string lblCaptain {
            get {
                return ResourceManager.GetString("lblCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string lblGoals {
            get {
                return ResourceManager.GetString("lblGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string lblHomeTeam {
            get {
                return ResourceManager.GetString("lblHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblNumber {
            get {
                return ResourceManager.GetString("lblNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblPlayerName {
            get {
                return ResourceManager.GetString("lblPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a representation.
        /// </summary>
        public static string lblRepresentation {
            get {
                return ResourceManager.GetString("lblRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a resolution.
        /// </summary>
        public static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string lblYellowCards {
            get {
                return ResourceManager.GetString("lblYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string rlblCountry {
            get {
                return ResourceManager.GetString("rlblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code.
        /// </summary>
        public static string rlblFifaCode {
            get {
                return ResourceManager.GetString("rlblFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string rlblNumberOfDraws {
            get {
                return ResourceManager.GetString("rlblNumberOfDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games lost.
        /// </summary>
        public static string rlblNumberOfGamesLost {
            get {
                return ResourceManager.GetString("rlblNumberOfGamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played.
        /// </summary>
        public static string rlblNumberOfGamesPlayed {
            get {
                return ResourceManager.GetString("rlblNumberOfGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won.
        /// </summary>
        public static string rlblNumberOfGamesWon {
            get {
                return ResourceManager.GetString("rlblNumberOfGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals against.
        /// </summary>
        public static string rlblNumberOfGoalsAgainst {
            get {
                return ResourceManager.GetString("rlblNumberOfGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals differential.
        /// </summary>
        public static string rlblNumberOfGoalsDifferential {
            get {
                return ResourceManager.GetString("rlblNumberOfGoalsDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for.
        /// </summary>
        public static string rlblNumberOfGoalsFor {
            get {
                return ResourceManager.GetString("rlblNumberOfGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string tabPlayers {
            get {
                return ResourceManager.GetString("tabPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string tabTeams {
            get {
                return ResourceManager.GetString("tabTeams", resourceCulture);
            }
        }
    }
}
